# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: enquete.proto for package 'mypackage.enquete'

require 'grpc'
require_relative 'enquete_pb'

module Mypackage
  module Enquete
    module EnqueteService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mypackage.enquete.EnqueteService'

        rpc :ListEnquete, ::Mypackage::Enquete::ListEnqueteRequest, ::Mypackage::Enquete::ListEnqueteResponse
        rpc :GetEnquete, ::Mypackage::Enquete::GetEnqueteRequest, ::Mypackage::Enquete::GetEnqueteResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
