# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'mypackage.user'

require 'grpc'
require_relative 'user_pb'

module Mypackage
  module User
    module UserService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mypackage.user.UserService'

        rpc :ListUser, ::Mypackage::User::ListUserRequest, ::Mypackage::User::ListUserResponse
        rpc :GetUser, ::Mypackage::User::GetUserRequest, ::Mypackage::User::GetUserResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
